### ISSUE TITLE
"Fatal error: Uncaught Error: Class 'Mustangostang\Spyc' not found in phar" test failure

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/package-command#12]
From #11

```
(::) failed steps (::)
01. $ /tmp/wp-cli-test-run-59255fc6881718.50526158/wp-cli-build-59255fc68875b4.95509327.phar package install path-command
    
    Fatal error: Uncaught Error: Class 'Mustangostang\Spyc' not found in phar:///tmp/wp-cli-test-run-59255fc6881718.50526158/wp-cli-build-59255fc68875b4.95509327.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Configurator.php:303
    Stack trace:
    #0 phar:///tmp/wp-cli-test-run-59255fc6881718.50526158/wp-cli-build-59255fc68875b4.95509327.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Configurator.php(219): WP_CLI\Configurator::load_yml('/tmp/wp-cli-pac...')
    #1 phar:///tmp/wp-cli-test-run-59255fc6881718.50526158/wp-cli-build-59255fc68875b4.95509327.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(680): WP_CLI\Configurator->merge_yml('/tmp/wp-cli-pac...', NULL)
    #2 phar:///tmp/wp-cli-test-run-59255fc6881718.50526158/wp-cli-build-59255fc68875b4.95509327.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/ConfigureRunner.php(23): WP_CLI\Runner->init_config()
    #3 phar:///tmp/wp-cli-test-run-59255fc6881718.50526158/wp-cli-build-59255fc68875b4.95509327.phar/vendor/wp-cli/wp-cli/php/bootstrap.php(75): WP_CLI\Bootstrap\ConfigureRunner->process(Object(WP_CLI\Bootstrap in phar:///tmp/wp-cli-test-run-59255fc6881718.50526158/wp-cli-build-59255fc68875b4.95509327.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Configurator.php on line 303
```

**Comment by schlessera** [comment]
Should be a Travis caching issue (probably due to Travis switching branches). These will hopefully disappear once we've rolled out the bootstrap refactor everywhere.

For now, clearing the Travis cache should solve this,.

**Comment by schlessera** [comment]
Oh, no, looks like I've been to quick to dismiss this. One of the tests seems to pull in a combination of incompatible package versions...

**Comment by schlessera** [comment]
The phar-building seems to ignore the version that is requested by the test.

As an example, in the test `Install a package requiring a WP-CLI version that doesn't match`, a phar is built using the version string `"0.23.0"`.

However, looking at the error output, it runs the new bootstrap refactor code, like `WP_CLI\Bootstrap\ConfigureRunner`, which was clearly not part of version 0.23.0.

**Comment by schlessera** [comment]
The actual error, that the class `Mustangostang\Spyc` is missing, is probably due to the fact that the **new** WP-CLI framework is pulled into the phar through the **old** `make-phar.sh`, which does not take that package into account.

**Comment by schlessera** [comment]
See https://github.com/wp-cli/wp-cli/issues/4095

**Comment by joehoyle** [comment]
Hmm I think I'm stilling getting this with 1.2.1:

```
Fatal error: Uncaught Error: Class 'Spyc' not found in phar:///usr/local/bin/wp/vendor/wp-cli/mustangostang-spyc/includes/functions.php:20
Stack trace:
#0 /usr/src/app/dictator/php/class-dictator-cli-command.php(218): spyc_load('#\n# This is a D...')
#1 /usr/src/app/dictator/php/class-dictator-cli-command.php(79): Dictator_CLI_Command->load_state_file('content/state-n...')
#2 [internal function]: Dictator_CLI_Command->impose(Array, Array)
#3 phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php(67): call_user_func(Array, Array, Array)
#4 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#5 phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php(401): call_user_func(Object(Closure), Array, Array)
#6 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(323): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
#7 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(330): WP_CLI\Runner->run_command(Array, Array)
#8 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(929):  in phar:///usr/local/bin/wp/vendor/wp-cli/mustangostang-spyc/includes/functions.php on line 20
```

**Comment by danielbachhuber** [comment]
@joehoyle It looks like Dictator is the origin of it. If you're not using it actively, you can uninstall. If you are using it actively, feel free to open an issue in that repo and I'll help track down the source.
