### ISSUE TITLE
Broke composer commands when used with phpcodesniffer-composer-installer

### ISSUE THREAD

**Issue by mickaelperrin** [wp-cli/package-command#99]
Hi,

I am not sure which one is causing the issue, but I just noticed that using at the same time this package with `dealerdirect/phpcodesniffer-composer-installer` broke composer post install commands.

## Steps to reproduce
1. Create a minimal composer.json file:
```
{
  "require": {
    "php": ">=7.0.0"
  },
	"require-dev": {
		"wp-cli/package-command": "*@stable",
		"dealerdirect/phpcodesniffer-composer-installer": "*"
	},
  "scripts": {
    "post-install-message": [
      "echo 'Oooops'"
    ],
    "post-install-cmd": [
      "composer run post-install-message"
    ],
    "post-update-cmd": [
      "composer run post-install-message"
    ]
  }
}
```

2. Run `composer install`

## Result

```
> post-update-cmd: composer run post-install-message
Executing command (CWD): composer run post-install-message

Fatal error: Uncaught Error: Class 'Symfony\Component\Process\ProcessBuilder' not found in /src/test/vendor/dealerdirect/phpcodesniffer-composer-installer/src/Plugin.php:118
Stack trace:
#0 /src/test/vendor/dealerdirect/phpcodesniffer-composer-installer/src/Plugin.php(103): Dealerdirect\Composer\Plugin\Installers\PHPCodeSniffer\Plugin->init()
#1 /src/test/vendor/composer/composer/src/Composer/Plugin/PluginManager.php(236): Dealerdirect\Composer\Plugin\Installers\PHPCodeSniffer\Plugin->activate(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
#2 /src/test/vendor/composer/composer/src/Composer/Plugin/PluginManager.php(205): Composer\Plugin\PluginManager->addPlugin(Object(Dealerdirect\Composer\Plugin\Installers\PHPCodeSniffer\Plugin))
#3 /src/test/vendor/composer/composer/src/Composer/Plugin/PluginManager.php(261): Composer\Plugin\PluginManager->registerPackage(Object(Composer\Package\CompletePackage))
#4 /src/test/vendor/composer/composer/src/Composer/Plugin/PluginManager.php(76): Composer\Plugin\PluginManager->loa in /src/test/vendor/dealerdirect/phpcodesniffer-composer-installer/src/Plugin.php on line 118
Script composer run post-install-message handling the post-update-cmd event returned with error code 255

```

It has been crossposted to https://github.com/Dealerdirect/phpcodesniffer-composer-installer/issues/59

Thanks

**Comment by frenck** [comment]
This issue has been identified as an upstream issue in the `dealerdirect/phpcodesniffer-composer-installer` package.

**Comment by schlessera** [comment]
Fixed upstream.
